name: lint-test
on: [pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install .
      - run: pip install pytest pytest-asyncio coverage ruff mypy
      - run: ruff .
      - run: mypy .
      - run: coverage run -m pytest
      - run: coverage report --fail-under=80
