name: nightly-dbt
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: dbt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install dbt-postgres
      - run: dbt run --project-dir dbt
      - run: dbt docs generate --project-dir dbt
