global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Application metrics (when we add metrics endpoint)
  - job_name: 'kafka-pipeline'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Assuming app runs on port 8000
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis metrics (if redis-exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (if postgres-exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 10s